### ISSUE TITLE
请问下有SM4-GCM模式加解密的实现方法吗？

### ISSUE THREAD

**Issue by liyangzbx** [Jxpro/sm4-file#1]

**Comment by Jxpro** [comment]
目前还没实现，给个star和watch，我这两天给你实现一下吧。

**Comment by Jxpro** [comment]
你那里有相关标准文档吗，128次多项式用AES-GCM标准里的吗？

**Comment by liyangzbx** [comment]
> 你那里有相关标准文档吗，128次多项式用AES-GCM标准里的吗？

嗯，应该是按照AES-GCM的方式实现。

**Comment by Jxpro** [comment]
由于代码结构的设计问题，没有考虑到附加消息的输入和mac的输出，所以在类结构上难以扩展GCM模式，除非大改；
由于大文件的分割方式，会产生多个mac，所以在UI上也难以集成GCM模式，除非多个mac再进行多次GF128乘法；
所以综上两点原因，我这里仅实现了不带附加消息的GCM模式，且未集成到UI中，希望可以作为参考。
另外我没找到AES-GCM的标准文件，下面是网上的一些参考资料：
https://ludvigknutsmark.github.io/posts/breaking_aes_gcm_part2/
https://blog.csdn.net/armlinuxww/article/details/115478717
